[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.80.0"

# This is a starter template for Netlify builds. See the following links for more:
# https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/

[[redirects]]
  from = "https://chefshop.coramsoftware.com/*"
  to = "https://35.230.45.9/:splat"
  status = 301
  force = true

